'use strict';

const fs = require('fs');
const path = require('path');

const key = process.env.TMDB_API_KEY || '';
const outPath = path.join(__dirname, '..', 'java', 'config.js');

const API_BASE = 'https://api.themoviedb.org/3/';
const IMG_BASE = 'https://image.tmdb.org/t/p/';
const POSTER_SIZE = 'w342';

const content = `// Auto-generated by scripts/generate-config.js
// Do NOT commit this file to git (should be listed in .gitignore)
window.TMDB_CONFIG = {
  TMDB_KEY: "${String(key).replace(/"/g, '\\"')}",
  API_BASE: "${API_BASE}",
  IMG_BASE: "${IMG_BASE}",
  POSTER_SIZE: "${POSTER_SIZE}"
};
`;

try {
  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
  console.log('[generate-config] wrote', outPath);
} catch (err) {
  console.error('[generate-config] error writing config.js', err);
  process.exit(1);
}
